name: Deploy to Dokku

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to dokku
        uses: tarantool/actions/dokku-deploy@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          dokku-app-name: rws${{ !startsWith(github.ref, 'refs/tags/') && '-dev' || '' }}
          git-push-flags: '--force'
      - name: Send notification on failure
        if: failure()
        uses: dasshit/myteam-notify@master
        with:
          api-url: https://api.internal.myteam.mail.ru/bot/v1/
          bot-token: ${{ secrets.VKTEAMS_TARANTOOLBOT_TOKEN }}
          chat-id: ${{ secrets.VKTEAMS_SERVICE_CHAT_ID }}
          msg-text: >
            Dokku deployment failure for ${{ github.repository }}:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
