name: Deploy to Dokku

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04-self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy to dokku
        uses: tarantool/actions/dokku-deploy@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          dokku-app-name: rws
          git-push-flags: '--force'
